theme = "hugo-theme-relearn"

baseURL = 'http://example.org/'

relativeURLs = false
uglyURLs = true

languageCode = 'en'
defaultContentLanguage = "en"

title = 'BetterGUI Documentation'

[markup.goldmark.renderer]
    unsafe = true

[outputFormats.llms]
mediaType = "text/plain"
baseName = "llms"
isPlainText = true

[outputFormats.llmsfull]
mediaType = "text/plain"
baseName = "llms-full"
isPlainText = true
